### PR TITLE
Fixes #357 - render breaks when form is not passed

### LINKED ISSUE #357: Cannot read "props" of undefined (formless field)
# Environment

* **react-advanaced-form:** 1.6.4

# What

## Current behavior
When rendering a field without a parent `Form`, it will throw the mentioned exception in the console.

## Expected behavior
Ideally, #216, yet for now need to add a better explanation of what the error is about.

# Why
Need to have good DX, errors must be transparent.

# How
1. Check `this.context.form` upon `Field` mount.
1. If `undefined`, throw a verbose error, prevent from attempting to register.

### PR DESCRIPTION
**Pull request by redraushan**
Closes #357

# Roadmap

- [x] Whenever a field is created without a Form passed to it through the context, a meaningful error must be displayed in the console
- [x] The rendering of the page must not be blocked; formless field returns null from its render method.

### CODE REVIEW

File: src/utils/error.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// @flow
```
Comment (redraushan) [inline src/utils/error.js]: Added error.js based on warning.js which is just another wrapper fir logging errors. Invariant wouldn't replace errors as the same will throw error and break the code execution which will result into broken render

File: src/components/createField.jsx [hunk 2]
```diff
@@ -84,8 +84,8 @@ export default function connectField(options) {
       }
 
       static contextTypes = {
-        form: PropTypes.object.isRequired,
```
Comment (redraushan) [inline src/components/createField.jsx]: Removed isRequired for form and field as, if the component is not wrapped with Form, it will throw PropTypes error before custom error message is shown.

File: src/components/createField.jsx [hunk 3]
```diff
@@ -96,8 +96,7 @@ export default function connectField(options) {
 
         /* Compose the field path */
         this.__fieldPath = fieldGroup ? [...fieldGroup, name] : [name]
-
-        invariant(
```
Comment (redraushan) [inline src/components/createField.jsx]: Removed invariant as it will throw exception and halt the component rendering, however, error just logs the message in console and render null if Form is not passed

**Comment by redraushan** [comment]
Hi @kettanaito please review :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

File: src/utils/error.js (hunk 1 above)
Comment (kettanaito) [reply src/utils/error.js]: Can we please use existing `warning`?
At this point formless fields are not an error per say. Its usage is expected, but yet not supported. I feel that a warning is a proper option here.

What do you think?

File: src/components/createField.jsx [hunk 4]
```diff
@@ -373,6 +372,7 @@ export default function connectField(options) {
 
       render() {
         const { props, contextProps } = this
+        if (!contextProps) return null
```
Comment (kettanaito) [inline src/components/createField.jsx]: Let's use the `warning` here to warn on using formless fields that are currently not supported.

We can use a similar text like:

```js
warning(true, 'Failed to render the field `%s`: expected to be a child of a Form component. Please render fields as children of Form, since formless fields are not currently supported.', props.name)
```

**Comment by kettanaito** [comment]
First of all, thank you for the first contribution, @redraushan!

Sorry it took me some time to get to your pull request. Looks great overall. Could you please see my comments?

File: src/utils/error.js (hunk 1 above)
Comment (redraushan) [reply src/utils/error.js]: Agree, we can deal it with warning for the time being until we have support for the formless field.

Should I remove the error.js file as well?

Comment (kettanaito) [reply src/utils/error.js]: Exactly. Once #216 is shipped, we can remove this warning.

File: src/components/createField.jsx (hunk 3 above)
Comment (kettanaito) [reply src/components/createField.jsx]: Please could you also remove the invariant import at the beginning of the file?
It's not used here after your changes.

File: src/components/createField.jsx (hunk 4 above)
Comment (redraushan) [reply src/components/createField.jsx]: Hi @kettanaito,

It should be warning(false,... not warning(true,...
I just copied exact same provided code and I was scratching my head why warning is not getting logged :D

File: src/components/createField.jsx [hunk 5]
```diff
@@ -373,6 +366,18 @@ export default function connectField(options) {
...
         const { props, contextProps } = this
+        
+        /* Render null and log warning in case of formless field */
+        if (!contextProps) {
+          warning(
+            false,
+            'Failed to render the field `%s`: expected to be a child ' +
+              'of a Form component. Please render fields as children of ' +
+              'Form, since formless fields are not currently supported.',
+            props.name,
```
Comment (kettanaito) [inline src/components/createField.jsx]: Sorry for not addressing this properly the first time, but we can use `this.__fieldPath.join('.')` instead of `props.name` for more descriptive field name. This will help to navigate which field is problematic in case of complex field path.

If there are two fields named `firstName`, but one is in the `groupA` group, and the second is in `groupB` group, it won't be enough to warn using the name only. Joining the field path will yield exact field path like `["groupA", "firstName"]` which would increase developer experience.

Could you please use it instead the name here?

Comment (redraushan) [reply src/components/createField.jsx]: Thanks for the quick review, PR updated.

**Comment by kettanaito** [comment]
Thank you and welcome your first contribution, @redraushan! 🎉 
Your changes are approved and merged.
